export const ROUTES = {
    HOME: "/home",
    FOLLOWING: "/following",
    COMPOSE: "/compose",
    SEARCH: "/search",
    SETTINGS: "/settings",
    LOGIN: "/login",
    REGISTER: "/register",
    ME: "/me",
    ME_EDIT: "/me/edit",
    ADMIN: "/admin",
    ADMIN_LOGIN: "/admin/login",
    ADMIN_USERS: "/admin/users",
    ADMIN_CONTENTS: "/admin/contents",
    ADMIN_COMMENTS: "/admin/comments",
    ADMIN_SETTINGS: "/admin/settings",
    user: (id: string | number) => `/user/${encodeURIComponent(String(id))}`,
    content: (id: string | number) => `/content/${encodeURIComponent(String(id))}`,
    contentEdit: (id: string | number) => `/content/${encodeURIComponent(String(id))}/edit`,
    searchQuery: (q: string) => `/search?q=${encodeURIComponent(q)}`,
    loginNext: (next: string) => `/login?next=${encodeURIComponent(next)}`,
} as const;
